project:
  name: quickstart-korea-isms-p
  regions:
  - ap-northeast-2
  - ap-southeast-1
  - ap-northeast-1
  - ap-southeast-2
  - us-east-2
  - eu-west-2
  s3_bucket: isms-configuration-846386179780
  
  
tests:
  default:
    template: ./templates/master.template
    regions:
      - ap-southeast-1
    parameters:
      EC2KeyPairBastion: isms_key
      EC2KeyPair: isms_key
      AvailabilityZoneA: ap-southeast-1a
      AvailabilityZoneB: ap-southeast-1c
      QSS3BucketName: isms-configuration-846386179780
      QSS3KeyPrefix: quickstart-korea-isms-p/
      #DBPassword: Password12#$
      NotificationList: kyeonjoo@amazon.com
  