project:
  name: quickstart-korea-isms-p
  regions:
  - ap-northeast-2
#  - ap-northeast-1
  s3_bucket: ''
tests:
  default:
    template: templates/isms-entrypoint-new-vpc.template.yaml
#    template: ./templates/master.template
    regions:
      - ap-northeast-2
#      - us-east-1
#      - us-west-2
#      - ap-southeast-1
    s3_regional_buckets: true
    parameters:
<<<<<<< HEAD
      EC2KeyPairBastion: isms_key
      EC2KeyPair: isms_key

      AvailabilityZoneA: $[taskcat_getsingleaz_1]
      AvailabilityZoneB: $[taskcat_getsingleaz_2]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
=======
      EC2KeyPairBastion: stage.seoul
      EC2KeyPair: stage.seoul
      AvailabilityZoneA: ap-northeast-2b
      AvailabilityZoneB: ap-northeast-2d
      QSS3BucketName: ks-isms-configuration
>>>>>>> 60fef2d... 	modified:   .taskcat.yml
      QSS3KeyPrefix: quickstart-korea-isms-p/
      DBPassword: P!$[taskcat_genpass_12A]
      CloudWatchLogsGroupName: $[taskcat_random-string]
