project:
  name: quickstart-korea-isms-p
  regions:
#  - ap-northeast-2
  - ap-northeast-1
  s3_bucket: ''
tests:
  default:
    template: templates/isms-entrypoint-new-vpc.template.yaml
#    template: ./templates/master.template
    regions:
      - ap-northeast-1
#      - us-east-1
#      - us-west-2
#      - ap-southeast-1
    s3_regional_buckets: true
    parameters:
      EC2KeyPairBastion: override
      EC2KeyPair: override

      AvailabilityZoneA: $[taskcat_getsingleaz_1]
      AvailabilityZoneB: $[taskcat_getsingleaz_2]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-korea-isms-p/
      DBPassword: P!$[taskcat_genpass_12A]
      CloudWatchLogsGroupName: $[taskcat_random-string]
